
AWSTemplateFormatVersion: '2010-09-09'
Description: 'Resume Analyzer Agents - Strands AgentCore Implementation - Infrastructure Resources'

Parameters:
  Environment:
    Type: String
    Default: 'agentcore'
    Description: Environment name for resource naming

Resources:
  # S3 Bucket for documents
  DocumentsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub 'amzn-s3-resume-analyzer-bucket-${Environment}-${AWS::AccountId}'
      VersioningConfiguration:
        Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

Outputs:
  DocumentsBucket:
    Description: 'S3 bucket for documents'
    Value: !Ref DocumentsBucket
    Export:
      Name: !Sub '${AWS::StackName}-DocumentsBucket'
